name: 'Minify-JSON'
author: 'Stefan Ensmann'
description: 'Minify JSON files'
inputs:
  input_file:
    description: 'The JSON file to minify'
    required: true
  output_file:
    description: 'The path to write the minified JSON file to. Overrides the given file by default.'
    required: false
runs:
  using: 'composite'
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
    - run: python minify.py ${{ inputs.input_file }}
      shell: bash
      if: ${{ inputs.output_file == ''}}
    - run: python minify.py ${{ inputs.input_file }} ${{ inputs.output_file }}
      shell: bash
      if: ${{ inputs.output_file != ''}}